
[project]
name = "radium226-pg_proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "construct>=2.10.70",
]

[project.scripts]
pg_proxy = "radium226.pg_proxy.cli:app"

[tool.uv]
package = true
dev-dependencies = [
  "psycopg2>=2.9.10",
  "pytest>=8.3.3",
  "radium226-pg",
]
